with open('input-q-1.txt') as f:
    txt = f.read()
    txt = txt.replace('one', '1')
    txt = txt.replace('two', '2')
    txt = txt.replace('three', '3')
    txt = txt.replace('four', '4')
    txt = txt.replace('five', '5')
    txt = txt.replace('six', '6')
    txt = txt.replace('seven', '7')
    txt = txt.replace('eight', '8')
    txt = txt.replace('nine', '9')
    txt = txt.replace('ten', '10')
    txt = txt.replace('eleven', '11')
    txt = txt.replace('twelve', '12')
    txt = txt.replace('thirteen', '13')
    txt = txt.replace('fourteen', '14')
    txt = txt.replace('fifteen', '15')
    txt = txt.replace('sixteen', '16')
    txt = txt.replace('seventeen', '17')
    txt = txt.replace('eighteen', '18')
    txt = txt.replace('nineteen', '19')
    txt = txt.replace('twenty', '20')


res = open('output-q-1.txt', 'x')
res.write(txt)
res.close()
